# Generated by Django 5.1 on 2024-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_subscriber_company_name_subscriber_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зелёный'), ('yellow', 'Жёлтый'), ('black', 'Чёрный'), ('white', 'Белый'), ('pink', 'Розовый'), ('purple', 'Фиолетовый'), ('orange', 'Оранжевый'), ('grey', 'Серый')], max_length=20, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('children', 'Дети'), ('teens', 'Подростки'), ('women', 'Женщины'), ('new_arrivals', 'Новинки')], max_length=20, verbose_name='Категория')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Уход за изделием')),
                ('images', models.ImageField(upload_to='products/', verbose_name='Изображения')),
                ('colors', models.ManyToManyField(blank=True, to='email_app.color', verbose_name='Цвета')),
                ('sizes', models.ManyToManyField(blank=True, to='email_app.size', verbose_name='Размеры')),
            ],
        ),
    ]
