# Generated by Django 5.1 on 2024-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_product_ozon_link_product_wildberries_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
